foreground #e2e2ea
background #121319
cursor #b4c5ff
selection_background #b4c5ff
selection_foreground #002a78

color0 #0c0e14
color8 #8e909d
color1 #b4c5ff
color9 #b4c5ff
color2 #bac5f0
color10 #bac5f0
color3 #fcaaff
color11 #fcaaff
color4 #4e6fcc
color12 #4e6fcc
color5 #3a4569
color13 #3a4569
color6 #a357a9
color14 #a357a9
color7 #c4c6d4
color15 #e2e2ea
